name: push-checks

on:
  push:
    branches:
      - main

jobs:
  code_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Lint
        run: npm run test

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      # Deploy
